name: flutter_getx_boilerplate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  flutter_dotenv: ^5.0.2
  get: 4.6.6
  shared_preferences: 2.3.2
  wave: 0.2.2
  fluttertoast: 8.2.8
  flutter_easyloading: 3.0.5
  flutter_svg: 2.0.10+1
  flutter_staggered_grid_view: 0.7.0
  cached_network_image: 3.4.1
  scaled_app: ^2.3.0
  reactive_forms: ^17.0.1
  dio: ^5.7.0
  flutter_verification_code: ^1.1.7
  get_storage: ^2.1.1
  flutter_i18n: ^0.36.2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
